services:
  db:
    image: mariadb:11.4.2-noble
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: your_password
    networks:
      - wp-network

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm-alpine
    ports: 
      - "9070:9000"
    user: "1000:1000"
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.26.1-alpine
    restart: unless-stopped
    ports:
      - "8099:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
      - ./wordpress:/var/www/html
    networks:
      - wp-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    networks:
      - wp-network

volumes:
  db_data:
  wordpress_data:

networks:
  wp-network:
